default:
  image: maven:3.8.5-openjdk-18

stages:
  - build
  - test
  - scan
  - deploy-artifact

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml"
  MAVEN_DEBUG: "-e -X"
  GIT_DEPTH: 0
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache

compile-job:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  when: always
  only:
    - tags
    - pushes
    - merge_requests

test-job:
  stage: test
  needs: [ "compile-job" ]
  script:
    - mvn $MAVEN_CLI_OPTS clean test
  when: on_success
  only:
    - tags
    - pushes
    - merge_requests

#sonarqube-scan-job:
#  stage: scan
#  needs: [ "compile-job", "test-job" ]
#  script:
#    - mvn $MAVEN_CLI_OPTS clean install sonar:sonar
#  allow_failure: false
#  when: on_success
#  only:
#    - merge_requests
#    - tags
#    - develop
#    - master

release-deploy:
  stage: deploy-artifact
  needs: [ "compile-job", "test-job" ]
  artifacts:
    paths:
      - "**/*.jar"
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^(release\/)[0-9]+((\.|-)[0-9]+)*/
  script:
    - mvn versions:set -DnewVersion=$(cut -d / -f 2 <<< $CI_COMMIT_TAG) -DautoVersionSubmodules=true
    - mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true clean deploy -Dmaven.deploy.skip=snapshots

snapshot-deploy:
  stage: deploy-artifact
  needs: [ "compile-job", "test-job" ]
  artifacts:
    paths:
      - "**/*.jar"
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^(snapshot\/)[0-9]+((\.|-)[0-9]+)*/
  script:
    - mvn versions:set -DnewVersion=$(cut -d / -f 2 <<< $CI_COMMIT_TAG)-SNAPSHOT -DautoVersionSubmodules=true
    - mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true clean deploy -Dmaven.deploy.skip=releases